map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 1.0

inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /hokuyo, data_type: LaserScan, topic: /slam_bot/laser/scan, marking: true, clearing: true}
