local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 1
   publish_frequency: 1
   width: 20.0
   height: 20.0
   resolution: 0.05
   static_map: false
   rolling_window: true
